version: "3.8"

services:
  web:
    build: .
    container_name: sito_php
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/log/apache2
    restart: unless-stopped